### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by plonibarploni** [MosheWagner/Orayta-QT#45]
When orayta is running, and I click randomly inside the text window, it crashes. If run from the terminal, it says `Segmentation fault`. This occurs both when using the precompiled binaries, as well as when I compile it myself.

**Comment by plonibarploni** [comment]
I did some more testing, and it appears to be caused by libQt5WebKit.so.5, which is also giving [others](https://github.com/notepadqq/notepadqq/issues/496) some issues as well (and possibly related to [this](https://github.com/annulen/webkit/issues/562)).
I'm in middle of compiling the latest QtWebKit, and will update if it works when it finishes compiling.

This issue doesn't appear when compiled against Qt4, and even Qt5 if running within `gdb` or `valgrind`.

**Comment by plonibarploni** [comment]
It finally finished compiling, and now this is what I get:

> Thread 1 "orayta" received signal SIGSEGV, Segmentation fault.
0x00007ffff59d0506 in unsigned int WebCore::WidthIterator::advanceInternal<WebCore::SurrogatePairAwareTextIterator>(WebCore::SurrogatePairAwareTextIterator&, WebCore::GlyphBuffer*) () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5

And the backtrace:

> #0  0x00007ffff59d0506 in unsigned int WebCore::WidthIterator::advanceInternal<WebCore::SurrogatePairAwareTextIterator>(WebCore::SurrogatePairAwareTextIterator&, WebCore::GlyphBuffer*) () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#1  0x00007ffff59d552d in WebCore::WidthIterator::advance(int, WebCore::GlyphBuffer*) () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#2  0x00007ffff599b5c2 in WebCore::FontCascade::offsetForPositionForSimpleText(WebCore::TextRun const&, float, bool) const ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#3  0x00007ffff51729c1 in WebCore::InlineTextBox::offsetForPosition(float, bool) const () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#4  0x00007ffff51d4fd9 in WebCore::RenderTextLineBoxes::positionForPoint(WebCore::RenderText const&, WebCore::LayoutPoint const&) const ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007ffff5273a04 in WebCore::RenderText::positionForPoint(WebCore::LayoutPoint const&, WebCore::RenderRegion const*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007ffff53bc089 in WebCore::FrameSelection::contains(WebCore::LayoutPoint const&) () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007ffff587b058 in WebCore::EventHandler::handleMousePressEventSingleClick(WebCore::MouseEventWithHitTestResults const&) ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007ffff587bd1b in WebCore::EventHandler::handleMousePressEvent(WebCore::MouseEventWithHitTestResults const&) ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007ffff5881863 in WebCore::EventHandler::handleMousePressEvent(WebCore::PlatformMouseEvent const&) () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#10 0x00007ffff475107f in QWebPageAdapter::mousePressEvent(QMouseEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#11 0x00007ffff7f91719 in QWebPage::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5
#12 0x00007ffff7f93040 in QWebView::mouseDoubleClickEvent(QMouseEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5
#13 0x00007ffff729598f in QWidget::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7f949de in QWebView::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5
#15 0x00007ffff725682c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff725e64f in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff31f89a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff725d622 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff72b014b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff72b27ba in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff725682c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff725e0f4 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff31f89a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff3b46523 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007ffff3b47ff5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007ffff3b1f2eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007fffe72b91c0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#28 0x00007fffedaa7387 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffedaa75c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007fffedaa764c in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff32518ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff31f69ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff31ffa84 in QCoreApplication::exec() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x000055555556d30f in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at main.cpp:320
